### ISSUE TITLE
License for module?

### ISSUE THREAD

**Issue by ivoanjo** [danielcompton/ip-range-check#2]
Hello there!

Thank you very much for the cool little module -- it does exactly what I was looking for. I noticed that there's no license for the project, which complicates the use I was intending for it 😉

Have you considered adding a license to the code? I personally favour [GNU LGPLv3](https://choosealicense.com/licenses/lgpl-3.0/) for libraries, but [MIT](https://choosealicense.com/licenses/mit/) is also stupidly simple and to the point.

GitHub keeps a great site to help choose a license, if you need some tips: <https://choosealicense.com>.

Thanks, and rock on!

**Comment by danielcompton** [comment]
Hi there, this is licensed as MIT, it’s noted in the package.json.

**Comment by danielcompton** [comment]
I’ve just added a matching LICENSE file to make this clearer, thanks for the note!

**Comment by ivoanjo** [comment]
Great, thanks for the quick answer 👍
