### ISSUE TITLE
Suggestions for number of hosts

### ISSUE THREAD

**Issue by kenbenobi666** [danielcompton/ip-range-check#5]
Good afternoon!
Apologies for my ugly english

I would like to make a suggestion

When a complete network is placed, for example a /24, the script evaluates as 100% to 256 hosts always, but it is likely that we know that in that network we only have 50 hosts.

Is it possible to add a parameter to specify the number of hosts to represent 100%?

**Comment by danielcompton** [comment]
Sorry, I'm not quite sure what you mean by this?

> the script evaluates as 100% to 256 hosts always, but it is likely that we know that in that network we only have 50 hosts.

This library exports a single function `ipRangeCheck` which returns `true`/`false`.

**Comment by kenbenobi666** [comment]
Hi!

Thanks for answering!

The problem is that my 100% is not always 256 ... like this case of the example, the number of hosts is 55 ... since they are 51, the percentage of "alive" should be 92%. But since the script always calculates on 256 hosts, in this case, the percentage of "alive" is very low

_Number of IP online on 10.254.2.0/24: 55
Number of IP offline 10.254.2.0/24: 199
Total number of IP: 254
IPs online percentage is: 22%
IPs offline percentage is: 78%
CHECK-FPING OK_

**Comment by danielcompton** [comment]
Ok, I don't think this library is going to have what you need for this, feel free to fork it and pick out the pieces you need though.

Thanks!
